In [37]:
from sklearn import svm, datasets
iris = datasets.load_iris()

In [38]:
import pandas as pd
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[40:45]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
40                5.0               3.5                1.3               0.3   
41                4.5               2.3                1.3               0.3   
42                4.4               3.2                1.3               0.2   
43                5.0               3.5                1.6               0.6   
44                5.1               3.8                1.9               0.4   

    flower  
40  setosa  
41  setosa  
42  setosa  
43  setosa  
44  setosa

In [3]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(iris.data, iris.target, test_size=0.3)

In [4]:
from sklearn.model_selection import cross_val_score

In [5]:
cross_val_score(svm.SVC(kernel='linear',C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [6]:
cross_val_score(svm.SVC(kernel='rbf',C=10, gamma='auto'),iris.data, iris.target, cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [7]:
cross_val_score(svm.SVC(kernel='rbf',C=50, gamma='auto'),iris.data, iris.target, cv=5)

array([1.        , 0.96666667, 0.9       , 0.93333333, 1.        ])

In [8]:
import numpy as np
kernels = ['rbf', 'linear']
C =[1,10,20]
avg_score = {}
for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'), iris.data, iris.target, cv=5)
        avg_score[kval + '_' + str(cval)] = np.average(cv_scores)
        
avg_score

{'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668,
 'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666}

In [9]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'), {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False)

clf.fit(iris.data, iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00203819, 0.00083003, 0.0007906 , 0.00090222, 0.00078979,
        0.00058951]),
 'std_fit_time': array([0.00069819, 0.00049826, 0.00039576, 0.00019876, 0.00039512,
        0.00078162]),
 'mean_score_time': array([0.00112362, 0.00071211, 0.00060081, 0.00060167, 0.00091257,
        0.00023084]),
 'std_score_time': array([0.00067742, 0.000403  , 0.00049057, 0.00049128, 0.00050494,
        0.00038988]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [10]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.002038      0.000698         0.001124        0.000677       1   
1       0.000830      0.000498         0.000712        0.000403       1   
2       0.000791      0.000396         0.000601        0.000491      10   
3       0.000902      0.000199         0.000602        0.000491      10   
4       0.000790      0.000395         0.000913        0.000505      20   
5       0.000590      0.000782         0.000231        0.000390      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [11]:
df[['param_C','param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.980000
1       1       linear         0.980000
2      10          rbf         0.980000
3      10       linear         0.973333
4      20          rbf         0.966667
5      20       linear         0.966667

In [12]:
clf.best_score_

0.9800000000000001

In [13]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

Hyper parameter

In [14]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [49]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params':{
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }
    },
    'random_forest': {
    'model': RandomForestClassifier(),
    'params':{
        'n_estimators':[1,5,10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    }
}

In [50]:
scores = []
for model_name, mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'], cv=5, return_train_score=False)
    clf.fit(iris.data, iris.target)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [51]:
df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 1}
2  logistic_regression    0.966667                   {'C': 5}

Exercise

In [88]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
from sklearn import datasets
digits = datasets.load_digits()

In [103]:
model_param = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params':{
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }
    },
    'random_forest': {
    'model': RandomForestClassifier(),
    'params':{
        'n_estimators':[1,5,10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params':{
            'C':[1,5,10]
        }
    },
    'naive_bayes_gaussian': {
        'model': GaussianNB(),
        'params':{
        }
        
    },
    'multinomianb': {
        'model': MultinomialNB(force_alpha=True),
        'params':{
        }
    },
    'decition_tree_classifier':{
        'model': DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy'],
        }
    }
}

In [104]:
score = []
for model_name, mp in model_param.items():
    clf = GridSearchCV(mp['model'],mp['params'], cv=5, return_train_score=False)
    clf.fit(digits.data, digits.target)
    score.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })

In [105]:
df1 = pd.DataFrame(score, columns=['model','best_score','best_params'])
df1

model  best_score                   best_params
0                       svm    0.947697  {'C': 1, 'kernel': 'linear'}
1             random_forest    0.902098          {'n_estimators': 10}
2       logistic_regression    0.922114                      {'C': 1}
3      naive_bayes_gaussian    0.806928                            {}
4              multinomianb    0.870350                            {}
5  decition_tree_classifier    0.809701      {'criterion': 'entropy'}

In [106]:
df1

model  best_score                   best_params
0                       svm    0.947697  {'C': 1, 'kernel': 'linear'}
1             random_forest    0.902098          {'n_estimators': 10}
2       logistic_regression    0.922114                      {'C': 1}
3      naive_bayes_gaussian    0.806928                            {}
4              multinomianb    0.870350                            {}
5  decition_tree_classifier    0.809701      {'criterion': 'entropy'}

In [109]:
df1.sort_values(by=['best_score'], ascending=False)

model  best_score                   best_params
0                       svm    0.947697  {'C': 1, 'kernel': 'linear'}
2       logistic_regression    0.922114                      {'C': 1}
1             random_forest    0.902098          {'n_estimators': 10}
4              multinomianb    0.870350                            {}
5  decition_tree_classifier    0.809701      {'criterion': 'entropy'}
3      naive_bayes_gaussian    0.806928                            {}