In [23]:
import numpy as np

In [29]:
from sklearn.datasets import load_digits

digits = load_digits()
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [30]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [31]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test,y_test)

0.9888888888888889

In [33]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test,y_test)

0.9703703703703703

In [45]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=9)
kf

KFold(n_splits=9, random_state=None, shuffle=False)

In [46]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [47]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [48]:
get_score(LogisticRegression(),x_train, x_test, y_train, y_test)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9592592592592593

In [49]:
get_score(SVC(),x_train, x_test, y_train, y_test)

0.9888888888888889

In [50]:
get_score(RandomForestClassifier(),x_train, x_test, y_train, y_test)

0.9703703703703703

In [53]:
from sklearn.model_selection import StratifiedKFold
fold = StratifiedKFold(n_splits=3)

Main code of k Fold
    

In [54]:
from sklearn.model_selection import cross_val_score

In [57]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [58]:
cross_val_score(LinearRegression(),digits.data,digits.target)

array([0.48346048, 0.5583603 , 0.57534522, 0.5056632 , 0.40995457])

In [61]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data,digits.target)

array([0.92222222, 0.91388889, 0.95264624, 0.95821727, 0.9275766 ])

In [62]:
cross_val_score(RandomForestClassifier(n_estimators=50),digits.data,digits.target)

array([0.93055556, 0.9       , 0.95543175, 0.95821727, 0.92200557])